src/Entity/User/Account.php
<?php

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="users_accounts")
 * @ORM\Entity()
 */
class Account
{
    /**
     * @var string
     *
     * @ORM\Id()
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $uuid;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $position;

    /**
     * @var \App\Entity\User\User
     *
     * @ORM\OneToOne(targetEntity="App\Entity\User\User", inversedBy="account")
     * @ORM\JoinColumn(name="user_uuid", referencedColumnName="uuid")
     */
    private $user;

    /**
     * @var \App\Entity\Account\Account
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Account\Account", inversedBy="users")
     * @ORM\JoinColumn(name="account_uuid", referencedColumnName="uuid")
     */
    private $account;

    /**
     * @return string
     */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * @return string|null
     */
    public function getPosition(): ?string
    {
        return $this->position;
    }

    /**
     * @param string|null $position
     */
    public function setPosition(?string $position): void
    {
        $this->position = $position;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return \App\Entity\Account\Account|null
     */
    public function getAccount(): ?\App\Entity\Account\Account
    {
        return $this->account;
    }

    /**
     * @param \App\Entity\Account\Account $account
     */
    public function setAccount(?\App\Entity\Account\Account $account): void
    {
        $this->account = $account;
    }
}

src/Entity/User/User.php
<?php

namespace App\Entity\User;

use App\Entity\Workflow;
use App\Entity\WorkflowTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\Repository\User\UserRepository")
 *
 * @UniqueEntity(fields={"email"})
 */
class User
{
    use WorkflowTrait;

    /**
     * @var string
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $uuid;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     */
    private $fname;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     */
    private $lname;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $sname;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default"=1})
     */
    private $isActive;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default"=0})
     */
    private $isConfirmed;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_mobile;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $skype;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true, length=65536)
     */
    private $comments;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\User\Password", mappedBy="user", cascade={"persist", "remove"})
     * @ORM\OrderBy({"createdAt": "DESC"})
     */
    private $passwords;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\User\Checkword", mappedBy="user", cascade={"persist", "remove"})
     * @ORM\OrderBy({"createdAt": "DESC"})
     */
    private $checkwords;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Role")
     * @ORM\JoinTable(name="users_roles",
     *     joinColumns={@ORM\JoinColumn(name="user_uuid", referencedColumnName="uuid")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="role_uuid", referencedColumnName="uuid")}
     * )
     */
    private $roles;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Site")
     * @ORM\JoinTable(name="users_sites",
     *     joinColumns={@ORM\JoinColumn(name="user_uuid", referencedColumnName="uuid")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="site_uuid", referencedColumnName="uuid")}
     * )
     */
    private $sites;

    /**
     * @var \App\Entity\User\Account|null
     *
     * @ORM\OneToOne(targetEntity="App\Entity\User\Account", mappedBy="user", cascade={"persist"})
     */
    private $account;

    /**
     * @var string
     */
    private $password;

    /**
     * User constructor.
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        $defaults = [
            'passwords' => new ArrayCollection(),
            'checkwords' => new ArrayCollection(),
            'roles' => new ArrayCollection(),
            'sites' => new ArrayCollection(),
            'isActive' => true,
            'isConfirmed' => false,
        ];

        $attributes = array_merge($defaults, $attributes);

        foreach ($attributes as $attribute => $value) {
            $method = strpos($attribute, '+') === 0
                ? 'add' . ucfirst(substr($attribute, 1))
                : 'set' . ucfirst($attribute);

            if (method_exists($this, $method)) {
                $this->$method($value);
            }
        }
    }

    /**
     * User cloning.
     */
    public function __clone()
    {
        $attributes = [
            'passwords' => new ArrayCollection(),
            'checkwords' => new ArrayCollection(),
            'workflow' => new Workflow()
        ];

        foreach ($attributes as $name => $value) {
            $this->$name = $value;
        }
    }

    /**
     * @return string|null
     */
    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string|null
     */
    public function getFname(): ?string
    {
        return $this->fname;
    }

    /**
     * @param string $fname
     */
    public function setFname(string $fname): void
    {
        $this->fname = $fname;
    }

    /**
     * @return string|null
     */
    public function getLname(): ?string
    {
        return $this->lname;
    }

    /**
     * @param string $lname
     */
    public function setLname(string $lname): void
    {
        $this->lname = $lname;
    }

    /**
     * @return string|null
     */
    public function getSname(): ?string
    {
        return $this->sname;
    }

    /**
     * @param string|null $sname
     */
    public function setSname(?string $sname): void
    {
        $this->sname = $sname;
    }

    /**
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * @param string|null $phone
     */
    public function setPhone(?string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return string|null
     */
    public function getPhoneMobile(): ?string
    {
        return $this->phone_mobile;
    }

    /**
     * @param string|null $phone_mobile
     */
    public function setPhoneMobile(?string $phone_mobile): void
    {
        $this->phone_mobile = $phone_mobile;
    }

    /**
     * @return string|null
     */
    public function getSkype(): ?string
    {
        return $this->skype;
    }

    /**
     * @param string|null $skype
     */
    public function setSkype(?string $skype): void
    {
        $this->skype = $skype;
    }

    /**
     * @return \DateTime|null
     */
    public function getBirthdate(): ?\DateTime
    {
        return $this->birthdate;
    }

    /**
     * @param \DateTime|null $birthdate
     */
    public function setBirthdate(?\DateTime $birthdate): void
    {
        $this->birthdate = $birthdate;
    }

    /**
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->comments;
    }

    /**
     * @param string|null $comments
     */
    public function setComments(?string $comments): void
    {
        $this->comments = $comments;
    }

    /**
     * @return ArrayCollection
     */
    public function getSites(): ?Collection
    {
        return $this->sites;
    }

    /**
     * @param ArrayCollection $sites
     */
    public function setSites(ArrayCollection $sites): void
    {
        $this->sites = $sites;
    }

    /**
     * @return ArrayCollection
     */
    public function getPasswords(): Collection
    {
        return $this->passwords;
    }

    /**
     * @param ArrayCollection $passwords
     */
    public function setPasswords(ArrayCollection $passwords): void
    {
        $this->passwords = $passwords;
    }

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param Password $password
     */
    public function setPassword(Password $password): void
    {
        $this->getPasswords()->add($password);
    }

    /**
     * @return ArrayCollection
     */
    public function getCheckwords(): Collection
    {
        return $this->checkwords;
    }

    /**
     * @param ArrayCollection $checkwords
     */
    public function setCheckwords(ArrayCollection $checkwords): void
    {
        $this->checkwords = $checkwords;
    }

    /**
     * @param Checkword $checkword
     */
    public function setCheckword(Checkword $checkword)
    {
        $this->getCheckwords()->add($checkword);
    }

    /**
     * @return Collection
     */
    public function getRoles(): Collection
    {
        return $this->roles;
    }

    /**
     * @param ArrayCollection $roles
     */
    public function setRoles(ArrayCollection $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     */
    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    /**
     * @return bool
     */
    public function isConfirmed(): bool
    {
        return $this->isConfirmed;
    }

    /**
     * @param bool $isConfirmed
     */
    public function setIsConfirmed(bool $isConfirmed): void
    {
        $this->isConfirmed = $isConfirmed;
    }

    /**
     * @return string
     */
    public function getFullName(): string
    {
        return trim($this->fname . ' ' . $this->lname);
    }

    /**
     * @return Account|null
     */
    public function getAccount(): ?Account
    {
        return $this->account;
    }

    /**
     * @param Account $account
     */
    public function setAccount(Account $account): void
    {
        if (!$account->getUser()) {
            $account->setUser($this);
        }

        $this->account = $account;
    }
}

src/Form/User/AccountType.php
<?php

namespace App\Form\User;

use App\Entity\User\Account;
use App\Repository\Account\AccountRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class AccountType
 *
 * @package App\Form\User
 */
class AccountType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('account', EntityType::class, [
                'label' => 'form.account.label',
                'help' => 'form.account.help',
                'placeholder' => 'form.account.placeholder',
                'class' => \App\Entity\Account\Account::class,
                'choice_label' => 'title',
                'query_builder' => function (AccountRepository $repository) {
                    return $repository->available();
                },
            ])
            ->add('position', TextType::class, [
                'required' => false,
                'label' => 'form.position.label',
                'help' => 'form.position.help',
                'attr' => ['placeholder' => 'form.position.placeholder']
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Account::class
        ]);
    }
}

src/Controller/Users/UsersController.php
<?php

namespace App\Controller\Users;

use App\Annotation\AjaxRequest;
use App\Entity\User\User;
use App\Service\User\UserService;
use App\Tools\Paginator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation as Http;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class UsersController
 *
 * @Route("/users")
 * @package App\Controller\Users
 */
class UsersController extends AbstractController
{
    /**
     * @Route("/{page<\d+>?1}", name="users:index", methods={"GET"})
     *
     * @param Http\Request $request
     * @param int $page
     *
     * @return Http\Response
     */
    public function index(Http\Request $request, int $page): Http\Response
    {
        $repository = $this->getDoctrine()->getRepository(User::class);

        $viewFile = "users/users/index.html.twig";
        if ($request->isXmlHttpRequest()) {
            $viewFile = "users/users/_index.html.twig";
        }

        return $this->render($viewFile, [
            'rows' => new Paginator($repository->search($request->get('search')), $page),
        ]);
    }

    /**
     * @Route("/add", name="users:add", methods={"GET","POST"})
     *
     * @param UserService $service
     *
     * @return Http\Response
     */
    public function add(UserService $service): Http\Response
    {
        return $service->process('/users/users/add.html.twig', new User());
    }

    /**
     * @Route("/{uuid}/edit", name="users:edit", methods={"GET","POST"})
     *
     * @param User $user
     * @param UserService $service
     *
     * @return Http\Response
     */
    public function edit(User $user, UserService $service): Http\Response
    {
        return $service->process('/users/users/edit.html.twig', $user);
    }

    /**
     * @Route("/{uuid}/copy", name="users:copy", methods={"GET","POST"})
     *
     * @param User $user
     * @param UserService $service
     *
     * @return Http\Response
     */
    public function copy(User $user, UserService $service): Http\Response
    {
        return $service->process('/users/users/copy.html.twig', clone $user);
    }

    /**
     * @Route("/{uuid?batch}/delete", name="users:delete", methods={"GET","DELETE"})
     * @AjaxRequest()
     *
     * @return Http\Response
     */
    public function delete(): Http\Response
    {
        return new Http\Response();
    }
}

templates/users/users/_form.html.twig
{% set nav = [
    ['tabs.properties', 'properties'],
    ['tabs.permissions', 'access'],
    ['tabs.extra', 'extra'],
] %}
{{ form_start(form, {'attr': {'novalidate': true}}) }}

{% for message in app.session.flashBag.get('success') %}
    <div class="alert alert--success">
        {{ message | trans }}
    </div>
{% endfor %}

<div class="tabs">
    <ul class="tabs__nav">
        {% for item in nav %}
            <li class="tabs__item">
                <a class="tabs__link{% if loop.first %} tabs__link--active{% endif %}" href="#{{ item[1] }}" data-toggle="tab" data-target="#{{ item[1] }}">{{ item[0] | trans({}, 'users') }}</a>
            </li>
        {% endfor %}
    </ul>
    <div class="tabs__panels">
        {% for item in nav %}
            <div class="tabs__panel{% if loop.first %} tabs__panel--active{% endif %}" id="{{ item[1] }}">
                {{ include('/users/users/_form_' ~ item[1] ~ '.html.twig') }}
            </div>
        {% endfor %}
    </div>
    <div class="tabs__footer">
        {{ form_widget(form.save) }}
        {{ form_widget(form.apply) }}
        <a href="{{ path('users:index') }}" class="btn btn--default">
            {{ 'form.button.cancel' | trans }}
        </a>
    </div>
</div>
{{ form_end(form) }}

templates/users/users/_form_access.html.twig
<div class="grid">
    <div class="grid__column">
        <h2>User roles</h2>
        <hr />
        {{ form_row(form.roles, {label: false}) }}
        <button type="button" class="btn btn--default" data-toggle="selection" data-target="#{{ form.roles.vars.id }}">
            {{ 'form.button.selection' | trans() }}
        </button>
    </div>
    <div class="grid__column">
        <h2>User sites</h2>
        <hr />
        {{ form_row(form.sites, {label: false}) }}
        <button type="button" class="btn btn--default" data-toggle="selection" data-target="#{{ form.sites.vars.id }}">
            {{ 'form.button.selection' | trans() }}
        </button>
    </div>
</div>

templates/users/users/_form_extra.html.twig
<div class="grid">
    <div class="grid__column">
        <h2>Company</h2>

        <hr />

        {{ form_row(form.account.account) }}
        {{ form_row(form.account.position) }}

        <br />

        <h2>Change password</h2>

        <hr />

        <div class="grid">
            <div class="grid__column">
                {{ form_row(form.password.first) }}
            </div>
            <div class="grid__column">
                {{ form_row(form.password.second) }}
            </div>
            <div class="grid__column" style="flex-grow: 0;">
                <div class="form__group">
                    <label class="form__label">&nbsp;</label>
                    <button data-toggle="password" class="btn btn--default">{{ 'form.password.generate' | trans({}, 'users') }}</button>
                </div>
            </div>
        </div>

    </div>
    <div class="grid__column">
        <h2>Extra information</h2>

        <div class="grid">
            <div class="grid__column">
                Registered:
                {% if user.workflow is not null %}
                    {{ user.workflow.createdAt | date }}
                    {% if user.workflow.created is not null %}
                        ({{ user.workflow.created.fullName }})
                    {% endif %}
                {% else %}
                    {{ 'general.not_available' | trans }}
                {% endif %}
            </div>
                <div class="grid__column">
                Updated:
                {% if user.workflow is not null %}
                    {{ user.workflow.updatedAt | date }}
                    {% if user.workflow.created is not null %}
                        ({{ user.workflow.updated.fullName }})
                    {% endif %}
                {% else %}
                    {{ 'general.not_available' | trans }}
                {% endif %}
            </div>
        </div>

        <br />

        <h2>Passwords history</h2>

        {% if user.passwords.count > 0 %}
        <table class="table">
            <thead class="table__head">
            <tr class="table__row">
                <th class="table__item table__item--head">Issue date</th>
                <th class="table__item table__item--head">Expire date</th>
                <th class="table__item table__item--head">Is valid</th>
            </tr>
            </thead>
            <tbody class="table__body">
            {% for password in user.passwords %}
                <tr class="table__row">
                    <td class="table__item">{{ password.createdAt | date }}</td>
                    <td class="table__item">{{ password.expiredAt | date }}</td>
                    <td class="table__item">
                        {% if password.isValid %}
                            <svg width="24" height="24"><use xlink:href="#svg-check"></use></svg>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <div><em>{{ 'passwords.empty' | trans({}, 'users') }}</em></div>
        {% endif %}

    </div>
</div>

templates/users/users/_form_properties.html.twig
<div class="grid">
    <div class="grid__column">
        <div class="grid">
            <div class="grid__column">
                {{ form_row(form.isActive) }}
            </div>
            <div class="grid__column">
                {{ form_row(form.isConfirmed) }}
            </div>
        </div>
        {{ form_row(form.email) }}
        <div class="grid">
            <div class="grid__column">
                {{ form_row(form.fname) }}
            </div>
            <div class="grid__column">
                {{ form_row(form.lname) }}
            </div>
        </div>
        <div class="grid">
            <div class="grid__column">
                {{ form_row(form.sname) }}
            </div>
            <div class="grid__column">
                {{ form_row(form.birthdate) }}
            </div>
        </div>
        <hr />
        <div class="grid">
            <div class="grid__column">
                {{ form_row(form.phone) }}
            </div>
            <div class="grid__column">
                {{ form_row(form.phoneMobile) }}
            </div>
        </div>
        {{ form_row(form.skype) }}
    </div>
    <div class="grid__column">
        <div class="user-avatar">
            <div class="user-avatar__image">
                {{ 'form.avatar.no_image' | trans({}, 'users') }}
            </div>
            <div class="user-avatar__button">
                <button class="btn btn--default">{{ 'form.avatar.select' | trans({}, 'users') }}</button>
            </div>
            <div class="user-avatar__notes">
                {{ 'form.avatar.notes' | trans({}, 'users') }}
            </div>
        </div>
    </div>
</div>

templates/users/users/_index.context.html.twig
{% extends "context.html.twig" %}

{% set items = [
    [
        {
            "title": 'context.menu.edit' | trans({}, 'users'),
            "url": path('users:edit', {'uuid': row.uuid}),
        },
        {
            "title": 'context.menu.copy' | trans({}, 'users'),
            "url": path('users:copy', {'uuid': row.uuid}),
        }
    ],
    [
        {
            "title": 'context.menu.delete' | trans({}, 'users'),
            "url": path('users:delete', {'uuid': row.uuid}),
            "attr": {
                'data-toggle': 'modal',
                'data-target': '#confirm-modal',
                'data-remote': 'true'
            }
        }
    ]
] %}

templates/users/users/_index.html.twig
{% extends "_spreadsheet.html.twig"  %}

{% block spreadsheet_table %}
    <table class="table">
        <colgroup>
            <col width="54">
            <col span="2">
            <col width="100" span="2">
            <col width="12%" span="2">
            <col width="40">
        </colgroup>
        <thead class="table__head">
        <tr class="table__row">
            <th class="table__item table__item--head">
                <div class="checkbox checkbox--table">
                    <label class="checkbox__label checkbox__label--table">
                        <input type="checkbox" class="checkbox__input checkbox__input--table" data-toggle="table-select-all">
                    </label>
                </div>
            </th>
            {% set headers = [
                { 'title': 'table.head.fullname', 'code': 'fullname' },
                { 'title': 'table.head.email', 'code': 'email' },
                { 'title': 'table.head.active', 'code': 'active', 'attr': {'class': 'table__item table__item--head table__item--center'} },
                { 'title': 'table.head.confirmed', 'code': 'confirmed', 'attr': {'class': 'table__item table__item--head table__item--center'} },
                { 'title': 'table.head.login', 'code': 'login' },
                { 'title': 'table.head.modified', 'code': 'modified' }
            ] %}
            {% for header in headers %}
                <th class="table__item table__item--head">
                    <a href="{{ path('users:index', {'sort': header.code}) }}" class="table__sort" data-update="#spreadsheet">{{ header.title | trans({}, 'users') }}</a>
                </th>
            {% endfor %}
            <th class="table__item table__item--head table__item--icon">
                <svg width="24" height="24"><use xlink:href="#svg-menu"></use></svg>
            </th>
        </tr>
        </thead>
        <tbody class="table__body">
        {% for row in rows %}
            <tr class="table__row">
                <td class="table__item">
                    <div class="checkbox checkbox--table">
                        <label class="checkbox__label checkbox__label--table">
                            <input type="checkbox" class="checkbox__input checkbox__input--table" data-toggle="table-select" value="{{ row.uuid }}">
                        </label>
                    </div>
                </td>
                <td class="table__item">
                    <span class="table-item__title">
                        <a href="{{ path('users:edit', {'uuid': row.uuid}) }}">{{ row.fullName }}</a>
                    </span>
                </td>
                <td class="table__item">
                    <a href="mailto:{{ row.email }}" target="_blank">{{ row.email }}</a>
                </td>
                <td class="table__item table__item--center">
                    {% if row.isActive %}
                        <svg width="24" height="24"><use xlink:href="#svg-check"></use></svg>
                    {% endif %}
                </td>
                <td class="table__item table__item--center">
                    {% if row.isConfirmed %}
                        <svg width="24" height="24"><use xlink:href="#svg-check"></use></svg>
                    {% endif %}
                </td>
                <td class="table__item">
                    <em>{{ 'general.not_available' | trans }}</em>
                </td>
                <td class="table__item">
                    {% if row.workflow is not null %}
                        {{ row.workflow.updatedAt | date }}
                    {% else %}
                        <em>{{ 'general.not_available' | trans }}</em>
                    {% endif %}
                </td>
                <td class="table__item table__item--dropdown">
                    <div class="dropdown dropdown--table">
                        <a class="dropdown__toggle dropdown__toggle--icon" data-toggle="dropdown">
                            <svg width="24" height="24"><use xlink:href="#svg-menu"></use></svg>
                        </a>
                        <ul class="dropdown__menu dropdown__menu--right">
                            {% include('users/users/_index.context.html.twig') %}
                        </ul>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block spreadsheet_pagination %}
    <div data-update="#spreadsheet">
    {{ include('pagination.html.twig', {
        'paginator': rows,
        'path': 'users:index'
    }) }}
    </div>
{% endblock %}

{% block toolbar_buttons %}
    {{ include('users/users/_index.toolbar.html.twig') }}
{% endblock %}

templates/users/users/_index.toolbar.html.twig
<div class="btn-group" role="group">
    <div class="btn-group__item">
        <a class="btn btn--default" href="{{ path('users:add') }}">
            {{ 'toolbar.btn.add' | trans({}, 'users') }}
        </a>
    </div>
</div>
<div class="btn-group" role="group">
    <div class="btn-group__item">
        <a class="btn btn--default btn--icon btn--disabled" href="{{ path('users:delete', {'batch': true}) }}" data-disabled="true" data-watch="checked" data-toggle="modal" data-target="#confirm-modal">
            <svg width="24" height="24"><use xlink:href="#svg-delete"></use></svg>
        </a>
    </div>
    <div class="btn-group__item">
        <a class="btn btn--default btn--icon" href="{{ path('users:index', {'page': rows.page}) }}" data-update="#spreadsheet" data-history="false">
            <svg width="24" height="24"><use xlink:href="#svg-refresh"></use></svg>
        </a>
    </div>
</div>

templates/users/users/add.html.twig
{% extends 'main.html.twig' %}

{% block title %}Users / New user{% endblock %}

{% block content %}

    {{ include('users/users/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('form') }}
    {{ encore_entry_script_tags('users') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('form') }}
    {{ encore_entry_link_tags('users') }}
{% endblock %}

templates/users/users/copy.html.twig
{% extends 'main.html.twig' %}

{% block title %}Users / Copy user{% endblock %}

{% block content %}

    {{ include('users/users/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('form') }}
    {{ encore_entry_script_tags('users') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('form') }}
    {{ encore_entry_link_tags('users') }}
{% endblock %}

templates/users/users/edit.html.twig
{% extends 'main.html.twig' %}

{% block title %}Users / Edit user{% endblock %}

{% block content %}

    {{ include('users/users/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('form') }}
    {{ encore_entry_script_tags('users') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('form') }}
    {{ encore_entry_link_tags('users') }}
{% endblock %}

templates/users/users/index.html.twig
{% extends 'spreadsheet.html.twig' %}

{% block title %}Users{% endblock %}

{% block spreadsheet %}
    {{ include('users/users/_index.html.twig') }}
{% endblock %}